### ISSUE TITLE
Recommendation: add lots of teams as contributors with write access

### ISSUE THREAD

**Issue by mgwalker** [18F/the-glossary#28]
Currently in order to create a pull request, I would need to fork this repo. To enable TTSers to push branches instead of needing to fork, I recommend adding teams from the 18F GitHub org as collaborators to the repo and giving them at least write permission. This list of teams is maybe not comprehensive, but it goes a long way:

- @18F/18f-staff 
- @18F/cloud-gov 
- @18F/identity 
- @18F/pif 
- @18F/solutions 
- @18F/tts-tech-portfolio 
- @18F/coes

**Comment by beechnut** [comment]
Thanks for the rec! Done!
