### ISSUE TITLE
Add new term: CHCO

### ISSUE THREAD

**Issue by beechnut** [18F/the-glossary#38]
Please fill in the following information to add a new term to the glossary. If you want to add multiple terms, copy the below list for each separate term. (See the bottom of this issue for an example.)

- **Term:** Chief Human Capital Officer
- **Acronym:** CHCO (pronounced chee-co, so maybe include CHICO)
- **Description:** [Find a definition here](https://www.gsa.gov/about-us/organization/leadership-directory/chief-human-capital-officer)

**Comment by alia-salim** [comment]
Closed via #53
