### ISSUE TITLE
Add new term: PKI

### ISSUE THREAD

**Issue by ajfarkas** [18F/the-glossary#45]
Please fill in the following information to add a new term to the glossary. If you want to add multiple terms, copy the below list for each separate term. (See the bottom of this issue for an example.)

- **Term:** Public Key Infrastructure
- **Acronym:** PKI
- **Description:** Public Key Infrastructure (PKI) is a framework established to issue, maintain, and revoke public key certificates, including systems, processes and people. Public key certificates provide digital signature and encryption capabilities.

**Comment by alia-salim** [comment]
Closed via #53
