### ISSUE TITLE
Add new term: TLC

### ISSUE THREAD

**Issue by claireb-gsa** [18F/the-glossary#50]
Please fill in the following information to add a new term to the glossary. If you want to add multiple terms, copy the below list for each separate term. (See the bottom of this issue for an example.)

- **Term:** Tender Loving Care
- **Acronym:** TLC
- **Description:** The TLC crew is a team within 18F made up of available staff who are between projects with partners. [TLC Crew Github](https://github.com/18F/TLC-crew)

**Comment by alia-salim** [comment]
Closed via #53
